import { Property } from "@/types/global";

export const properties: Property[] = [
    {
        id: "564d6g4df54gfdg",
        imageLink: '/ce9724a3-a985-44c0-b92a-acb35a1ca502.webp',
        type: 'villa',
        title: 'فيلا الزمرد 362',
        link: '/projects/emerald-362',
        rooms: '9 غرف نوم',
        beds: '7 حمامات',
        area: '650 متر مربع',
        location: 'جدة، حي الزمرد',
    },
    {
        id: "hdd45d5",
        imageLink: '/ce9724a3-a985-44c0-b92a-acb35a1ca502.webp',
        type: 'villa',
        title: 'فيلا الزمرد 362',
        link: '/projects/emerald-362',
        rooms: '9 غرف نوم',
        beds: '7 حمامات',
        area: '650 متر مربع',
        location: 'جدة، حي الزمرد',
    },
    {
        id: "skljsds5d5s",
        imageLink: '/ce9724a3-a985-44c0-b92a-acb35a1ca502.webp',
        type: 'villa',
        title: 'فيلا الزمرد 362',
        link: '/projects/emerald-362',
        rooms: '9 غرف نوم',
        beds: '7 حمامات',
        area: '650 متر مربع',
        location: 'جدة، حي الزمرد',
    },
    {
        id: "dkkdk55d6",
        imageLink: '/ce9724a3-a985-44c0-b92a-acb35a1ca502.webp',
        type: 'villa',
        title: 'فيلا الزمرد 362',
        link: '/projects/emerald-362',
        rooms: '9 غرف نوم',
        beds: '7 حمامات',
        area: '650 متر مربع',
        location: 'جدة، حي الزمرد',
    },
    {
        id: "ddls4s5",
        imageLink: '/ce9724a3-a985-44c0-b92a-acb35a1ca502.webp',
        type: 'villa',
        title: 'فيلا الزمرد 362',
        link: '/projects/emerald-362',
        rooms: '9 غرف نوم',
        beds: '7 حمامات',
        area: '650 متر مربع',
        location: 'جدة، حي الزمرد',
    },
    {
        id: "kdkdss",
        imageLink: '/ce9724a3-a985-44c0-b92a-acb35a1ca502.webp',
        type: 'villa',
        title: 'فيلا الزمرد 362',
        link: '/projects/emerald-362',
        rooms: '9 غرف نوم',
        beds: '7 حمامات',
        area: '650 متر مربع',
        location: 'جدة، حي الزمرد',
    },
    {
        id: "sjks7s4s",
        imageLink: '/ce9724a3-a985-44c0-b92a-acb35a1ca502.webp',
        type: 'villa',
        title: 'فيلا الزمرد 362',
        link: '/projects/emerald-362',
        rooms: '9 غرف نوم',
        beds: '7 حمامات',
        area: '650 متر مربع',
        location: 'جدة، حي الزمرد',
    },
    {
        id: "kdols445d",
        imageLink: '/ce9724a3-a985-44c0-b92a-acb35a1ca502.webp',
        type: 'villa',
        title: 'فيلا الزمرد 362',
        link: '/projects/emerald-362',
        rooms: '9 غرف نوم',
        beds: '7 حمامات',
        area: '650 متر مربع',
        location: 'جدة، حي الزمرد',
    },
];
