import type { Metadata } from "next";
import "../../src/styles/globals.css";

export const metadata: Metadata = {
  title: {
    template: "%s | مراسل جدة العقاري",
    default: "مراسل جدة العقاري"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body className="flex flex-col">
        {children}
      </body>
    </html>
  );
}
